### ISSUE TITLE
Error if document has unicode characters

### ISSUE THREAD

**Issue by e2045** [brrd/msoconvert#1]
Hello,

my document has unicode characters. But this error occured. 

> Error: Command failed: "c:\Users\myUser\Tool\node_modules\msoconvert\bin\docto.exe" --word --inputfile "C:\Users\myUser\test.doc"  --outputfile "C:\Users\myUser\test.txt"  --format wdFormatText msoEncodingUTF8
> 
>     at ChildProcess.exithandler (child_process.js:308:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1048:16)
>     at Socket.<anonymous> (internal/child_process.js:439:11)
>     at Socket.emit (events.js:315:20)
>     at Pipe.<anonymous> (net.js:673:12) {
>   killed: false,
>   code: 200,
>   signal: null,
>   cmd: '"c:\\Users\\myUser\\Tool\\node_modules\\msoconvert\\bin\\docto.exe" --word --inputfile "C:\\Users\\myUser\\test.doc"  --outputfile "C:\\Users\\myUser\\test.txt"  --format wdFormatText msoEncodingUTF8'
> }

Here is my code.

```
    const convert = require("msoconvert");
    convert({
        use: 'WD',
        input: inputFileDoc, 
        output: outputFileTXT, 
        format: 'wdFormatText', 
        options: 'msoEncodingUTF8',
    })
    .then(() => console.log("done"))
    .catch((error) => {
        console.log(error)
    });
```

Could you help me to handle this issue?

Thank you in advance.

**Comment by brrd** [comment]
Referring to https://github.com/tobya/DocTo, I think the correct parameter for `options` is: 
```
options: '-E msoEncodingUTF8'
```

**Comment by e2045** [comment]
> Referring to https://github.com/tobya/DocTo, I think the correct parameter for `options` is:
> 
> ```
> options: '-E msoEncodingUTF8'
> ```

Thank you for your reply. I tried like you said, but error still occurs

> Error: Command failed: "c:\Users\myUser\Tool\node_modules\msoconvert\bin\docto.exe" --word --inputfile "C:\Users\myUser\test.doc" --outputfile "C:\Users\myUser\test.txt" --format wdFormatText -E msoEncodingUTF8
> 
>     at ChildProcess.exithandler (child_process.js:308:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1048:16)
>     at Socket.<anonymous> (internal/child_process.js:439:11)
>     at Socket.emit (events.js:315:20)
>     at Pipe.<anonymous> (net.js:673:12) {
> killed: false,
> code: 400,
> signal: null,
> cmd: '"c:\Users\myUser\Tool\node_modules\msoconvert\bin\docto.exe" --word --inputfile "C:\Users\myUser\test.doc" --outputfile "C:\Users\myUser\test.txt" --format wdFormatText -E msoEncodingUTF8'
> }
>

**Comment by brrd** [comment]
Here is the output when running the command directly from docto.exe:

> Exiting with Error 400: EConvertError
> 'msoEncodingUTF8' is not a valid integer value

For some reason `msoEncodingUTF8` is not recognized by DocTo as a valid enum. But using directly [its integer value](https://docs.microsoft.com/fr-fr/office/vba/api/Office.MsoEncoding) seems to work as expected:

```
docto.exe --word --inputfile "test.doc" --outputfile "test.txt" --format wdFormatText -E 65001
```

So please try:
```
options: '-E 65001'
```

In any case we need to log better errors with msoconvert.

**Comment by e2045** [comment]
thank you. It works.

**Comment by tobya** [comment]
Yes, `-E` is an integer.  

I should make that more explicit in the help.  I should also provide a better error message!
